name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./WebAppDotnetCore
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      #working-directory: ./WebAppDotnetCore
      run: dotnet restore
    - name: Build
      #working-directory: ./WebAppDotnetCore
      run: dotnet build --no-restore
    - name: Test
      #working-directory: ./WebAppDotnetCore
      run: dotnet test --no-build --verbosity normal
      
    - name: dotnet publish
      #working-directory: ./WebApp1
      run: dotnet publish -c Release -o myapp
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-github-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./WebApp1/myapp
